# Generated by Django 5.0.2 on 2024-06-08 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Oncurepackages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('oncurepackage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='app.oncurepackages')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('mobile_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('coord_facilitator', models.CharField(max_length=255)),
                ('meals', models.CharField(max_length=255)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('current_department', models.CharField(blank=True, max_length=255, null=True)),
                ('assigned_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.department')),
                ('chosen_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.oncurepackages')),
            ],
        ),
        migrations.CreateModel(
            name='EnteredDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entered_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.department')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entered_departments', to='app.patient')),
            ],
        ),
    ]
