# Generated by Django 5.0.2 on 2024-06-12 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_coordinationfacilitators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='coord_facilitator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.coordinationfacilitators'),
        ),
    ]
