# Generated by Django 5.0.6 on 2024-06-05 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_registration_current_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='status',
            field=models.CharField(default='Free', max_length=255),
        ),
    ]
