# Generated by Django 5.0.2 on 2024-06-12 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_meals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='meals',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.meals'),
        ),
    ]
