# Generated by Django 5.0.6 on 2024-06-05 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_freedepartments'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusyDepartments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('patient', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='FreeDepartments',
        ),
    ]
