# Generated by Django 5.0.2 on 2024-06-17 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_patient_current_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='status',
        ),
        migrations.AddField(
            model_name='patient',
            name='consulting',
            field=models.BooleanField(default=False),
        ),
    ]
