# Generated by Django 5.0.2 on 2024-06-17 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_patient_status_patient_consulting'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
