# Generated by Django 5.0.2 on 2024-06-17 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_patient_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='consulting',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
