# Generated by Django 5.0.2 on 2024-06-17 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_patient_consulting'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='timer',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
