# Generated by Django 5.0.2 on 2024-06-17 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_patient_timer'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientSecondMiddle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chosentime', models.CharField(blank=True, max_length=255, null=True)),
                ('timer', models.DurationField(blank=True, null=True)),
                ('minutes', models.IntegerField()),
                ('hours', models.IntegerField()),
                ('currentdepartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.department')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Patient', to='app.patient')),
            ],
        ),
    ]
