# Generated by Django 5.0.2 on 2024-06-17 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_patientsecondmiddle_hours_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PatientSecondMiddle',
        ),
    ]
