# Generated by Django 5.0.2 on 2024-06-18 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_timer_timer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PatientSecondMiddle',
        ),
    ]
