# Generated by Django 5.0.2 on 2024-06-18 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_delete_patientsecondmiddle'),
    ]

    operations = [
        migrations.AddField(
            model_name='timer',
            name='currentdepartment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.department'),
        ),
        migrations.AddField(
            model_name='timer',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_timer', to='app.patient'),
        ),
    ]
