# Generated by Django 5.0.2 on 2024-06-18 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_timer_currentdepartment_timer_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='consulting',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='current_department',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='current_time',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='status',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='timer',
        ),
        migrations.AddField(
            model_name='patient',
            name='chosen_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='remaining_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='timer_active',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Timer',
        ),
    ]
