# Generated by Django 5.0.2 on 2024-06-23 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_remove_patient_consulting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
