# Generated by Django 5.0.2 on 2024-06-23 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_department_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='progress_bar',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
