# Generated by Django 5.0.2 on 2024-06-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_patient_progress_bar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='progress_bar',
            field=models.IntegerField(default=100),
        ),
    ]
