# Generated by Django 5.0.2 on 2024-06-24 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_patient_progress_bar'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='waiting_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='waiting_department', to='app.department'),
        ),
    ]
