# Generated by Django 5.0.2 on 2024-06-25 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_occupied_departments_patient_assignments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waiting_Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('oncurepackage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waiting_departments_package', to='app.oncurepackages')),
            ],
        ),
    ]
