# Generated by Django 5.0.2 on 2024-06-25 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_remove_patient_waiting_package_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EnteredDepartment',
        ),
    ]
