# Generated by Django 5.0.2 on 2024-06-25 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_delete_entereddepartment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_assignments',
            name='assigned',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_patient_assignments', to='app.department'),
        ),
        migrations.AlterField(
            model_name='patient_assignments',
            name='waiting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waiting_patient_assignments', to='app.department'),
        ),
    ]
