# Generated by Django 5.0.2 on 2024-06-25 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_alter_patient_assignments_assigned_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='occupied_departments',
            name='name',
        ),
        migrations.RemoveField(
            model_name='occupied_departments',
            name='oncurepackage',
        ),
        migrations.RemoveField(
            model_name='waiting_departments',
            name='name',
        ),
        migrations.RemoveField(
            model_name='waiting_departments',
            name='oncurepackage',
        ),
        migrations.AddField(
            model_name='occupied_departments',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.department'),
        ),
        migrations.AddField(
            model_name='waiting_departments',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.department'),
        ),
    ]
