# Generated by Django 5.0.2 on 2024-06-25 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_remove_occupied_departments_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='is_occupied',
            field=models.BooleanField(default=False),
        ),
    ]
