# Generated by Django 5.0.2 on 2024-06-25 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_department_is_occupied'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='is_occupied',
            new_name='is_assigned',
        ),
        migrations.AddField(
            model_name='department',
            name='is_waiting',
            field=models.BooleanField(default=False),
        ),
    ]
