# Generated by Django 5.0.2 on 2024-06-26 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_remove_department_is_assigned_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entered_Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entered_departments_department', to='app.department')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entered_departments_patients', to='app.patient')),
            ],
        ),
    ]
