# Generated by Django 5.0.2 on 2024-06-27 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_entered_departments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entered_departments',
            options={'ordering': ['patient', 'department']},
        ),
        migrations.CreateModel(
            name='Unentered_Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unentered_departments_department', to='app.department')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unentered_departments_patients', to='app.patient')),
            ],
            options={
                'ordering': ['patient', 'department'],
            },
        ),
    ]
