# Generated by Django 5.0.2 on 2024-06-27 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_alter_entered_departments_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='chosen_time',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='remaining_time',
        ),
        migrations.AddField(
            model_name='patient_assignments',
            name='chosen_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient_assignments',
            name='remaining_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
