# Generated by Django 5.0.2 on 2024-06-27 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_remove_patient_chosen_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='progress_bar',
        ),
        migrations.AddField(
            model_name='patient_assignments',
            name='progress_bar',
            field=models.IntegerField(default=100),
        ),
    ]
