# Generated by Django 5.0.2 on 2024-06-28 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_patient_assignments_remaining_departments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient_assignments',
            old_name='remaining_time',
            new_name='remaining_minute',
        ),
        migrations.AddField(
            model_name='patient_assignments',
            name='remaining_second',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient_assignments',
            name='total_minute',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient_assignments',
            name='total_second',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
