# Generated by Django 5.0.2 on 2024-06-28 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_rename_remaining_time_patient_assignments_remaining_minute_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='time',
            new_name='remaining_minutes',
        ),
        migrations.AddField(
            model_name='department',
            name='remaining_seconds',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
