# Generated by Django 5.0.2 on 2024-06-28 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_rename_time_department_remaining_minutes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient_assignments',
            old_name='remaining_minute',
            new_name='remaining_minutes',
        ),
    ]
