# Generated by Django 5.0.2 on 2024-06-28 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_rename_remaining_minute_patient_assignments_remaining_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_assignments',
            name='total_minute',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='patient_assignments',
            name='total_second',
            field=models.IntegerField(default=0),
        ),
    ]
