# Generated by Django 5.0.2 on 2024-06-30 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_patient_assignments_is_waiting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entered_departments',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entered_by_patients', to='app.department'),
        ),
        migrations.AlterField(
            model_name='entered_departments',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entered_departments', to='app.patient'),
        ),
    ]
